// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: proto/logs/log.proto

package logs

import (
	chiltrix "github.com/gonzojive/heatpump/proto/chiltrix"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeatpumpLogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=collection_time,json=collectionTime,proto3" json:"collection_time,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*HeatpumpLogEntry_RegisterValues
	//	*HeatpumpLogEntry_Error
	Value         isHeatpumpLogEntry_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatpumpLogEntry) Reset() {
	*x = HeatpumpLogEntry{}
	mi := &file_proto_logs_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatpumpLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatpumpLogEntry) ProtoMessage() {}

func (x *HeatpumpLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatpumpLogEntry.ProtoReflect.Descriptor instead.
func (*HeatpumpLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_logs_log_proto_rawDescGZIP(), []int{0}
}

func (x *HeatpumpLogEntry) GetCollectionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectionTime
	}
	return nil
}

func (x *HeatpumpLogEntry) GetValue() isHeatpumpLogEntry_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HeatpumpLogEntry) GetRegisterValues() *chiltrix.RegisterSnapshot {
	if x != nil {
		if x, ok := x.Value.(*HeatpumpLogEntry_RegisterValues); ok {
			return x.RegisterValues
		}
	}
	return nil
}

func (x *HeatpumpLogEntry) GetError() string {
	if x != nil {
		if x, ok := x.Value.(*HeatpumpLogEntry_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isHeatpumpLogEntry_Value interface {
	isHeatpumpLogEntry_Value()
}

type HeatpumpLogEntry_RegisterValues struct {
	RegisterValues *chiltrix.RegisterSnapshot `protobuf:"bytes,2,opt,name=register_values,json=registerValues,proto3,oneof"`
}

type HeatpumpLogEntry_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*HeatpumpLogEntry_RegisterValues) isHeatpumpLogEntry_Value() {}

func (*HeatpumpLogEntry_Error) isHeatpumpLogEntry_Value() {}

var File_proto_logs_log_proto protoreflect.FileDescriptor

const file_proto_logs_log_proto_rawDesc = "" +
	"\n" +
	"\x14proto/logs/log.proto\x12\x17gonzojive.heatpump.logs\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dproto/chiltrix/chiltrix.proto\"\xbf\x01\n" +
	"\x10HeatpumpLogEntry\x12C\n" +
	"\x0fcollection_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecollectionTime\x12E\n" +
	"\x0fregister_values\x18\x02 \x01(\v2\x1a.chiltrix.RegisterSnapshotH\x00R\x0eregisterValues\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\a\n" +
	"\x05valueB*Z(github.com/gonzojive/heatpump/proto/logsb\x06proto3"

var (
	file_proto_logs_log_proto_rawDescOnce sync.Once
	file_proto_logs_log_proto_rawDescData []byte
)

func file_proto_logs_log_proto_rawDescGZIP() []byte {
	file_proto_logs_log_proto_rawDescOnce.Do(func() {
		file_proto_logs_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logs_log_proto_rawDesc), len(file_proto_logs_log_proto_rawDesc)))
	})
	return file_proto_logs_log_proto_rawDescData
}

var file_proto_logs_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_logs_log_proto_goTypes = []any{
	(*HeatpumpLogEntry)(nil),          // 0: gonzojive.heatpump.logs.HeatpumpLogEntry
	(*timestamppb.Timestamp)(nil),     // 1: google.protobuf.Timestamp
	(*chiltrix.RegisterSnapshot)(nil), // 2: chiltrix.RegisterSnapshot
}
var file_proto_logs_log_proto_depIdxs = []int32{
	1, // 0: gonzojive.heatpump.logs.HeatpumpLogEntry.collection_time:type_name -> google.protobuf.Timestamp
	2, // 1: gonzojive.heatpump.logs.HeatpumpLogEntry.register_values:type_name -> chiltrix.RegisterSnapshot
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_logs_log_proto_init() }
func file_proto_logs_log_proto_init() {
	if File_proto_logs_log_proto != nil {
		return
	}
	file_proto_logs_log_proto_msgTypes[0].OneofWrappers = []any{
		(*HeatpumpLogEntry_RegisterValues)(nil),
		(*HeatpumpLogEntry_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logs_log_proto_rawDesc), len(file_proto_logs_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_logs_log_proto_goTypes,
		DependencyIndexes: file_proto_logs_log_proto_depIdxs,
		MessageInfos:      file_proto_logs_log_proto_msgTypes,
	}.Build()
	File_proto_logs_log_proto = out.File
	file_proto_logs_log_proto_goTypes = nil
	file_proto_logs_log_proto_depIdxs = nil
}
