// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.0
// source: proto/logs/log.proto

package logs

import (
	chiltrix "github.com/gonzojive/heatpump/proto/chiltrix"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeatpumpLogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=collection_time,json=collectionTime,proto3" json:"collection_time,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*HeatpumpLogEntry_RegisterValues
	//	*HeatpumpLogEntry_Error
	Value         isHeatpumpLogEntry_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeatpumpLogEntry) Reset() {
	*x = HeatpumpLogEntry{}
	mi := &file_proto_logs_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeatpumpLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeatpumpLogEntry) ProtoMessage() {}

func (x *HeatpumpLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logs_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeatpumpLogEntry.ProtoReflect.Descriptor instead.
func (*HeatpumpLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_logs_log_proto_rawDescGZIP(), []int{0}
}

func (x *HeatpumpLogEntry) GetCollectionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CollectionTime
	}
	return nil
}

func (x *HeatpumpLogEntry) GetValue() isHeatpumpLogEntry_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *HeatpumpLogEntry) GetRegisterValues() *chiltrix.RegisterSnapshot {
	if x != nil {
		if x, ok := x.Value.(*HeatpumpLogEntry_RegisterValues); ok {
			return x.RegisterValues
		}
	}
	return nil
}

func (x *HeatpumpLogEntry) GetError() string {
	if x != nil {
		if x, ok := x.Value.(*HeatpumpLogEntry_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isHeatpumpLogEntry_Value interface {
	isHeatpumpLogEntry_Value()
}

type HeatpumpLogEntry_RegisterValues struct {
	RegisterValues *chiltrix.RegisterSnapshot `protobuf:"bytes,2,opt,name=register_values,json=registerValues,proto3,oneof"`
}

type HeatpumpLogEntry_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*HeatpumpLogEntry_RegisterValues) isHeatpumpLogEntry_Value() {}

func (*HeatpumpLogEntry_Error) isHeatpumpLogEntry_Value() {}

var File_proto_logs_log_proto protoreflect.FileDescriptor

var file_proto_logs_log_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x2f, 0x6c, 0x6f, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x67, 0x6f, 0x6e, 0x7a, 0x6f, 0x6a, 0x69, 0x76,
	0x65, 0x2e, 0x68, 0x65, 0x61, 0x74, 0x70, 0x75, 0x6d, 0x70, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x68, 0x69, 0x6c, 0x74, 0x72, 0x69, 0x78,
	0x2f, 0x63, 0x68, 0x69, 0x6c, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xbf, 0x01, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x74, 0x70, 0x75, 0x6d, 0x70, 0x4c, 0x6f, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x43, 0x0a, 0x0f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x63, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x45, 0x0a, 0x0f, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x68, 0x69, 0x6c, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x48, 0x00,
	0x52, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6f, 0x6e, 0x7a, 0x6f, 0x6a, 0x69, 0x76, 0x65, 0x2f, 0x68, 0x65, 0x61, 0x74, 0x70, 0x75,
	0x6d, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_logs_log_proto_rawDescOnce sync.Once
	file_proto_logs_log_proto_rawDescData = file_proto_logs_log_proto_rawDesc
)

func file_proto_logs_log_proto_rawDescGZIP() []byte {
	file_proto_logs_log_proto_rawDescOnce.Do(func() {
		file_proto_logs_log_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_logs_log_proto_rawDescData)
	})
	return file_proto_logs_log_proto_rawDescData
}

var file_proto_logs_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_logs_log_proto_goTypes = []any{
	(*HeatpumpLogEntry)(nil),          // 0: gonzojive.heatpump.logs.HeatpumpLogEntry
	(*timestamppb.Timestamp)(nil),     // 1: google.protobuf.Timestamp
	(*chiltrix.RegisterSnapshot)(nil), // 2: chiltrix.RegisterSnapshot
}
var file_proto_logs_log_proto_depIdxs = []int32{
	1, // 0: gonzojive.heatpump.logs.HeatpumpLogEntry.collection_time:type_name -> google.protobuf.Timestamp
	2, // 1: gonzojive.heatpump.logs.HeatpumpLogEntry.register_values:type_name -> chiltrix.RegisterSnapshot
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_logs_log_proto_init() }
func file_proto_logs_log_proto_init() {
	if File_proto_logs_log_proto != nil {
		return
	}
	file_proto_logs_log_proto_msgTypes[0].OneofWrappers = []any{
		(*HeatpumpLogEntry_RegisterValues)(nil),
		(*HeatpumpLogEntry_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_logs_log_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_logs_log_proto_goTypes,
		DependencyIndexes: file_proto_logs_log_proto_depIdxs,
		MessageInfos:      file_proto_logs_log_proto_msgTypes,
	}.Build()
	File_proto_logs_log_proto = out.File
	file_proto_logs_log_proto_rawDesc = nil
	file_proto_logs_log_proto_goTypes = nil
	file_proto_logs_log_proto_depIdxs = nil
}
