load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "heatpump_lib",
    srcs = ["main.go"],
    importpath = "github.com/gonzojive/heatpump/cmd/heatpump",
    visibility = ["//visibility:private"],
    deps = [
        "//cmd/heatpump/logstats",
        "@com_github_golang_glog//:glog",
        "@com_github_spf13_cobra//:cobra",
        "@com_github_spf13_pflag//:pflag",
    ],
)

go_binary(
    name = "heatpump",
    embed = [":heatpump_lib"],
    visibility = ["//visibility:public"],
)
