// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: proto/fancoil/fancoil.proto

package fancoil

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemperatureUnits int32

const (
	TemperatureUnits_TEMPERATURE_UNITS_UNSPECIFIED TemperatureUnits = 0
	TemperatureUnits_TEMPERATURE_UNITS_CELCIUS     TemperatureUnits = 1
	TemperatureUnits_TEMPERATURE_UNITS_FAHRENHEIT  TemperatureUnits = 2
)

// Enum value maps for TemperatureUnits.
var (
	TemperatureUnits_name = map[int32]string{
		0: "TEMPERATURE_UNITS_UNSPECIFIED",
		1: "TEMPERATURE_UNITS_CELCIUS",
		2: "TEMPERATURE_UNITS_FAHRENHEIT",
	}
	TemperatureUnits_value = map[string]int32{
		"TEMPERATURE_UNITS_UNSPECIFIED": 0,
		"TEMPERATURE_UNITS_CELCIUS":     1,
		"TEMPERATURE_UNITS_FAHRENHEIT":  2,
	}
)

func (x TemperatureUnits) Enum() *TemperatureUnits {
	p := new(TemperatureUnits)
	*p = x
	return p
}

func (x TemperatureUnits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TemperatureUnits) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fancoil_fancoil_proto_enumTypes[0].Descriptor()
}

func (TemperatureUnits) Type() protoreflect.EnumType {
	return &file_proto_fancoil_fancoil_proto_enumTypes[0]
}

func (x TemperatureUnits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TemperatureUnits.Descriptor instead.
func (TemperatureUnits) EnumDescriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{0}
}

type FloorHeatingMode int32

const (
	FloorHeatingMode_FLOOR_HEATING_MODE_UNSPECIFIED FloorHeatingMode = 0
	FloorHeatingMode_FLOOR_HEATING_MODE_ON          FloorHeatingMode = 1
	FloorHeatingMode_FLOOR_HEATING_MODE_OFF         FloorHeatingMode = 2
)

// Enum value maps for FloorHeatingMode.
var (
	FloorHeatingMode_name = map[int32]string{
		0: "FLOOR_HEATING_MODE_UNSPECIFIED",
		1: "FLOOR_HEATING_MODE_ON",
		2: "FLOOR_HEATING_MODE_OFF",
	}
	FloorHeatingMode_value = map[string]int32{
		"FLOOR_HEATING_MODE_UNSPECIFIED": 0,
		"FLOOR_HEATING_MODE_ON":          1,
		"FLOOR_HEATING_MODE_OFF":         2,
	}
)

func (x FloorHeatingMode) Enum() *FloorHeatingMode {
	p := new(FloorHeatingMode)
	*p = x
	return p
}

func (x FloorHeatingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FloorHeatingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fancoil_fancoil_proto_enumTypes[1].Descriptor()
}

func (FloorHeatingMode) Type() protoreflect.EnumType {
	return &file_proto_fancoil_fancoil_proto_enumTypes[1]
}

func (x FloorHeatingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FloorHeatingMode.Descriptor instead.
func (FloorHeatingMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{1}
}

type ValveState int32

const (
	ValveState_VALVE_STATE_UNSPECIFIED ValveState = 0
	ValveState_VALVE_STATE_ON          ValveState = 1
	ValveState_VALVE_STATE_OFF         ValveState = 2
)

// Enum value maps for ValveState.
var (
	ValveState_name = map[int32]string{
		0: "VALVE_STATE_UNSPECIFIED",
		1: "VALVE_STATE_ON",
		2: "VALVE_STATE_OFF",
	}
	ValveState_value = map[string]int32{
		"VALVE_STATE_UNSPECIFIED": 0,
		"VALVE_STATE_ON":          1,
		"VALVE_STATE_OFF":         2,
	}
)

func (x ValveState) Enum() *ValveState {
	p := new(ValveState)
	*p = x
	return p
}

func (x ValveState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValveState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fancoil_fancoil_proto_enumTypes[2].Descriptor()
}

func (ValveState) Type() protoreflect.EnumType {
	return &file_proto_fancoil_fancoil_proto_enumTypes[2]
}

func (x ValveState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValveState.Descriptor instead.
func (ValveState) EnumDescriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{2}
}

type ValveSetting int32

const (
	ValveSetting_VALVE_SETTING_UNSPECIFIED ValveSetting = 0
	ValveSetting_VALVE_SETTING_ENABLED     ValveSetting = 1
	ValveSetting_VALVE_SETTING_DISABLED    ValveSetting = 2
)

// Enum value maps for ValveSetting.
var (
	ValveSetting_name = map[int32]string{
		0: "VALVE_SETTING_UNSPECIFIED",
		1: "VALVE_SETTING_ENABLED",
		2: "VALVE_SETTING_DISABLED",
	}
	ValveSetting_value = map[string]int32{
		"VALVE_SETTING_UNSPECIFIED": 0,
		"VALVE_SETTING_ENABLED":     1,
		"VALVE_SETTING_DISABLED":    2,
	}
)

func (x ValveSetting) Enum() *ValveSetting {
	p := new(ValveSetting)
	*p = x
	return p
}

func (x ValveSetting) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValveSetting) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fancoil_fancoil_proto_enumTypes[3].Descriptor()
}

func (ValveSetting) Type() protoreflect.EnumType {
	return &file_proto_fancoil_fancoil_proto_enumTypes[3]
}

func (x ValveSetting) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValveSetting.Descriptor instead.
func (ValveSetting) EnumDescriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{3}
}

type RegisterName int32

const (
	RegisterName_REGISTER_NAME_UNSPECIFIED                           RegisterName = 0
	RegisterName_REGISTER_NAME_ON_OFF                                RegisterName = 28301
	RegisterName_REGISTER_NAME_MODE                                  RegisterName = 28302
	RegisterName_REGISTER_NAME_FANSPEED                              RegisterName = 28303
	RegisterName_REGISTER_NAME_TIMER_OFF1                            RegisterName = 28306
	RegisterName_REGISTER_NAME_TIMER_OFF2                            RegisterName = 28307
	RegisterName_REGISTER_NAME_MAX_SET_TEMPERATURE                   RegisterName = 28308
	RegisterName_REGISTER_NAME_MIN_SET_TEMPERATURE                   RegisterName = 28309
	RegisterName_REGISTER_NAME_COOLING_SET_TEMPERATURE               RegisterName = 28310
	RegisterName_REGISTER_NAME_HEATING_SET_TEMPERATURE               RegisterName = 28311
	RegisterName_REGISTER_NAME_COOLING_SET_TEMPERATURE_AUTO          RegisterName = 28312
	RegisterName_REGISTER_NAME_HEATING_SET_TEMPERATURE_AUTO          RegisterName = 28313
	RegisterName_REGISTER_NAME_ANTI_COOLING_WIND_SETTING_TEMPERATURE RegisterName = 28314
	RegisterName_REGISTER_NAME_START_ANTI_HOT_WIND                   RegisterName = 28315
	RegisterName_REGISTER_NAME_START_ULTRA_LOW_WIND                  RegisterName = 28316
	RegisterName_REGISTER_NAME_USE_VALVE                             RegisterName = 28317
	RegisterName_REGISTER_NAME_USE_FLOOR_HEATING                     RegisterName = 28318
	RegisterName_REGISTER_NAME_USE_FAHRENHEIT                        RegisterName = 28319
	RegisterName_REGISTER_NAME_MASTER_SLAVE                          RegisterName = 28320
	RegisterName_REGISTER_NAME_UNIT_ADDRESS                          RegisterName = 28321
	RegisterName_REGISTER_NAME_ROOM_TEMPERATURE                      RegisterName = 46801
	RegisterName_REGISTER_NAME_COIL_TEMPERATURE                      RegisterName = 46802
	RegisterName_REGISTER_NAME_CURRENT_FAN_SPEED                     RegisterName = 46803
	RegisterName_REGISTER_NAME_FAN_RPM                               RegisterName = 46804
	RegisterName_REGISTER_NAME_VALVE_ON_OFF                          RegisterName = 46805
	RegisterName_REGISTER_NAME_REMOTE_ON_OFF                         RegisterName = 46806
	RegisterName_REGISTER_NAME_SIMULATION_SIGNAL                     RegisterName = 46807
	RegisterName_REGISTER_NAME_FAN_SPEED_SIGNAL_FEEDBACK_FAULT       RegisterName = 46808
	RegisterName_REGISTER_NAME_ROOM_TEMPERATURE_SENSOR_FAULT         RegisterName = 46809
	RegisterName_REGISTER_NAME_COIL_TEMPERATURE_SENSOR_FAULT         RegisterName = 46810
)

// Enum value maps for RegisterName.
var (
	RegisterName_name = map[int32]string{
		0:     "REGISTER_NAME_UNSPECIFIED",
		28301: "REGISTER_NAME_ON_OFF",
		28302: "REGISTER_NAME_MODE",
		28303: "REGISTER_NAME_FANSPEED",
		28306: "REGISTER_NAME_TIMER_OFF1",
		28307: "REGISTER_NAME_TIMER_OFF2",
		28308: "REGISTER_NAME_MAX_SET_TEMPERATURE",
		28309: "REGISTER_NAME_MIN_SET_TEMPERATURE",
		28310: "REGISTER_NAME_COOLING_SET_TEMPERATURE",
		28311: "REGISTER_NAME_HEATING_SET_TEMPERATURE",
		28312: "REGISTER_NAME_COOLING_SET_TEMPERATURE_AUTO",
		28313: "REGISTER_NAME_HEATING_SET_TEMPERATURE_AUTO",
		28314: "REGISTER_NAME_ANTI_COOLING_WIND_SETTING_TEMPERATURE",
		28315: "REGISTER_NAME_START_ANTI_HOT_WIND",
		28316: "REGISTER_NAME_START_ULTRA_LOW_WIND",
		28317: "REGISTER_NAME_USE_VALVE",
		28318: "REGISTER_NAME_USE_FLOOR_HEATING",
		28319: "REGISTER_NAME_USE_FAHRENHEIT",
		28320: "REGISTER_NAME_MASTER_SLAVE",
		28321: "REGISTER_NAME_UNIT_ADDRESS",
		46801: "REGISTER_NAME_ROOM_TEMPERATURE",
		46802: "REGISTER_NAME_COIL_TEMPERATURE",
		46803: "REGISTER_NAME_CURRENT_FAN_SPEED",
		46804: "REGISTER_NAME_FAN_RPM",
		46805: "REGISTER_NAME_VALVE_ON_OFF",
		46806: "REGISTER_NAME_REMOTE_ON_OFF",
		46807: "REGISTER_NAME_SIMULATION_SIGNAL",
		46808: "REGISTER_NAME_FAN_SPEED_SIGNAL_FEEDBACK_FAULT",
		46809: "REGISTER_NAME_ROOM_TEMPERATURE_SENSOR_FAULT",
		46810: "REGISTER_NAME_COIL_TEMPERATURE_SENSOR_FAULT",
	}
	RegisterName_value = map[string]int32{
		"REGISTER_NAME_UNSPECIFIED":                           0,
		"REGISTER_NAME_ON_OFF":                                28301,
		"REGISTER_NAME_MODE":                                  28302,
		"REGISTER_NAME_FANSPEED":                              28303,
		"REGISTER_NAME_TIMER_OFF1":                            28306,
		"REGISTER_NAME_TIMER_OFF2":                            28307,
		"REGISTER_NAME_MAX_SET_TEMPERATURE":                   28308,
		"REGISTER_NAME_MIN_SET_TEMPERATURE":                   28309,
		"REGISTER_NAME_COOLING_SET_TEMPERATURE":               28310,
		"REGISTER_NAME_HEATING_SET_TEMPERATURE":               28311,
		"REGISTER_NAME_COOLING_SET_TEMPERATURE_AUTO":          28312,
		"REGISTER_NAME_HEATING_SET_TEMPERATURE_AUTO":          28313,
		"REGISTER_NAME_ANTI_COOLING_WIND_SETTING_TEMPERATURE": 28314,
		"REGISTER_NAME_START_ANTI_HOT_WIND":                   28315,
		"REGISTER_NAME_START_ULTRA_LOW_WIND":                  28316,
		"REGISTER_NAME_USE_VALVE":                             28317,
		"REGISTER_NAME_USE_FLOOR_HEATING":                     28318,
		"REGISTER_NAME_USE_FAHRENHEIT":                        28319,
		"REGISTER_NAME_MASTER_SLAVE":                          28320,
		"REGISTER_NAME_UNIT_ADDRESS":                          28321,
		"REGISTER_NAME_ROOM_TEMPERATURE":                      46801,
		"REGISTER_NAME_COIL_TEMPERATURE":                      46802,
		"REGISTER_NAME_CURRENT_FAN_SPEED":                     46803,
		"REGISTER_NAME_FAN_RPM":                               46804,
		"REGISTER_NAME_VALVE_ON_OFF":                          46805,
		"REGISTER_NAME_REMOTE_ON_OFF":                         46806,
		"REGISTER_NAME_SIMULATION_SIGNAL":                     46807,
		"REGISTER_NAME_FAN_SPEED_SIGNAL_FEEDBACK_FAULT":       46808,
		"REGISTER_NAME_ROOM_TEMPERATURE_SENSOR_FAULT":         46809,
		"REGISTER_NAME_COIL_TEMPERATURE_SENSOR_FAULT":         46810,
	}
)

func (x RegisterName) Enum() *RegisterName {
	p := new(RegisterName)
	*p = x
	return p
}

func (x RegisterName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterName) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fancoil_fancoil_proto_enumTypes[4].Descriptor()
}

func (RegisterName) Type() protoreflect.EnumType {
	return &file_proto_fancoil_fancoil_proto_enumTypes[4]
}

func (x RegisterName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterName.Descriptor instead.
func (RegisterName) EnumDescriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{4}
}

type FanSetting int32

const (
	FanSetting_FAN_SETTING_UNSPECIFIED FanSetting = 0
	FanSetting_FAN_SETTING_OFF         FanSetting = 7
	FanSetting_FAN_SETTING_ULTRA_LOW   FanSetting = 1
	FanSetting_FAN_SETTING_LOW         FanSetting = 2
	FanSetting_FAN_SETTING_MEDIUM      FanSetting = 3
	FanSetting_FAN_SETTING_HIGH        FanSetting = 4
	FanSetting_FAN_SETTING_MAX         FanSetting = 5
	FanSetting_FAN_SETTING_AUTO        FanSetting = 6
)

// Enum value maps for FanSetting.
var (
	FanSetting_name = map[int32]string{
		0: "FAN_SETTING_UNSPECIFIED",
		7: "FAN_SETTING_OFF",
		1: "FAN_SETTING_ULTRA_LOW",
		2: "FAN_SETTING_LOW",
		3: "FAN_SETTING_MEDIUM",
		4: "FAN_SETTING_HIGH",
		5: "FAN_SETTING_MAX",
		6: "FAN_SETTING_AUTO",
	}
	FanSetting_value = map[string]int32{
		"FAN_SETTING_UNSPECIFIED": 0,
		"FAN_SETTING_OFF":         7,
		"FAN_SETTING_ULTRA_LOW":   1,
		"FAN_SETTING_LOW":         2,
		"FAN_SETTING_MEDIUM":      3,
		"FAN_SETTING_HIGH":        4,
		"FAN_SETTING_MAX":         5,
		"FAN_SETTING_AUTO":        6,
	}
)

func (x FanSetting) Enum() *FanSetting {
	p := new(FanSetting)
	*p = x
	return p
}

func (x FanSetting) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FanSetting) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fancoil_fancoil_proto_enumTypes[5].Descriptor()
}

func (FanSetting) Type() protoreflect.EnumType {
	return &file_proto_fancoil_fancoil_proto_enumTypes[5]
}

func (x FanSetting) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FanSetting.Descriptor instead.
func (FanSetting) EnumDescriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{5}
}

type PowerStatus int32

const (
	PowerStatus_POWER_STATUS_UNSPECIFIED PowerStatus = 0
	PowerStatus_POWER_STATUS_ON          PowerStatus = 1
	PowerStatus_POWER_STATUS_OFF         PowerStatus = 2
)

// Enum value maps for PowerStatus.
var (
	PowerStatus_name = map[int32]string{
		0: "POWER_STATUS_UNSPECIFIED",
		1: "POWER_STATUS_ON",
		2: "POWER_STATUS_OFF",
	}
	PowerStatus_value = map[string]int32{
		"POWER_STATUS_UNSPECIFIED": 0,
		"POWER_STATUS_ON":          1,
		"POWER_STATUS_OFF":         2,
	}
)

func (x PowerStatus) Enum() *PowerStatus {
	p := new(PowerStatus)
	*p = x
	return p
}

func (x PowerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fancoil_fancoil_proto_enumTypes[6].Descriptor()
}

func (PowerStatus) Type() protoreflect.EnumType {
	return &file_proto_fancoil_fancoil_proto_enumTypes[6]
}

func (x PowerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerStatus.Descriptor instead.
func (PowerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{6}
}

type Mode int32

const (
	Mode_MODE_UNSPECIFIED      Mode = 0
	Mode_MODE_AUTO             Mode = 5
	Mode_MODE_COOLING          Mode = 1
	Mode_MODE_DEHUMIDIFICATION Mode = 2
	Mode_MODE_VENTILATION      Mode = 3
	Mode_MODE_HEATING          Mode = 4
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		5: "MODE_AUTO",
		1: "MODE_COOLING",
		2: "MODE_DEHUMIDIFICATION",
		3: "MODE_VENTILATION",
		4: "MODE_HEATING",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED":      0,
		"MODE_AUTO":             5,
		"MODE_COOLING":          1,
		"MODE_DEHUMIDIFICATION": 2,
		"MODE_VENTILATION":      3,
		"MODE_HEATING":          4,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_fancoil_fancoil_proto_enumTypes[7].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_proto_fancoil_fancoil_proto_enumTypes[7]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{7}
}

type ModbusEnumValueOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegisterValue uint32                 `protobuf:"varint,1,opt,name=register_value,json=registerValue,proto3" json:"register_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModbusEnumValueOptions) Reset() {
	*x = ModbusEnumValueOptions{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModbusEnumValueOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModbusEnumValueOptions) ProtoMessage() {}

func (x *ModbusEnumValueOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModbusEnumValueOptions.ProtoReflect.Descriptor instead.
func (*ModbusEnumValueOptions) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{0}
}

func (x *ModbusEnumValueOptions) GetRegisterValue() uint32 {
	if x != nil {
		return x.RegisterValue
	}
	return 0
}

type GetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FancoilName   string                 `protobuf:"bytes,1,opt,name=fancoil_name,json=fancoilName,proto3" json:"fancoil_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateRequest) Reset() {
	*x = GetStateRequest{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateRequest) ProtoMessage() {}

func (x *GetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateRequest.ProtoReflect.Descriptor instead.
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{1}
}

func (x *GetStateRequest) GetFancoilName() string {
	if x != nil {
		return x.FancoilName
	}
	return ""
}

type GetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *State                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	RawSnapshot   *RawRegisterSnapshot   `protobuf:"bytes,2,opt,name=raw_snapshot,json=rawSnapshot,proto3" json:"raw_snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateResponse) Reset() {
	*x = GetStateResponse{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateResponse) ProtoMessage() {}

func (x *GetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateResponse.ProtoReflect.Descriptor instead.
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{2}
}

func (x *GetStateResponse) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *GetStateResponse) GetRawSnapshot() *RawRegisterSnapshot {
	if x != nil {
		return x.RawSnapshot
	}
	return nil
}

type RawRegisterSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawValues     map[uint32]uint32      `protobuf:"bytes,1,rep,name=raw_values,json=rawValues,proto3" json:"raw_values,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawRegisterSnapshot) Reset() {
	*x = RawRegisterSnapshot{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawRegisterSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawRegisterSnapshot) ProtoMessage() {}

func (x *RawRegisterSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawRegisterSnapshot.ProtoReflect.Descriptor instead.
func (*RawRegisterSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{3}
}

func (x *RawRegisterSnapshot) GetRawValues() map[uint32]uint32 {
	if x != nil {
		return x.RawValues
	}
	return nil
}

type State struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotTime                     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=snapshot_time,json=snapshotTime,proto3" json:"snapshot_time,omitempty"`
	PowerStatus                      PowerStatus            `protobuf:"varint,2,opt,name=power_status,json=powerStatus,proto3,enum=fancoil.PowerStatus" json:"power_status,omitempty"`
	Mode                             Mode                   `protobuf:"varint,3,opt,name=mode,proto3,enum=fancoil.Mode" json:"mode,omitempty"`
	RoomTemperature                  *Temperature           `protobuf:"bytes,4,opt,name=room_temperature,json=roomTemperature,proto3" json:"room_temperature,omitempty"`
	CoilTemperature                  *Temperature           `protobuf:"bytes,5,opt,name=coil_temperature,json=coilTemperature,proto3" json:"coil_temperature,omitempty"`
	PreferenceFanSetting             FanSetting             `protobuf:"varint,6,opt,name=preference_fan_setting,json=preferenceFanSetting,proto3,enum=fancoil.FanSetting" json:"preference_fan_setting,omitempty"`
	CurrentFanSetting                FanSetting             `protobuf:"varint,7,opt,name=current_fan_setting,json=currentFanSetting,proto3,enum=fancoil.FanSetting" json:"current_fan_setting,omitempty"`
	FanSpeed                         *FanSpeed              `protobuf:"bytes,8,opt,name=fan_speed,json=fanSpeed,proto3" json:"fan_speed,omitempty"`
	HeatingTargetTemperature         *Temperature           `protobuf:"bytes,9,opt,name=heating_target_temperature,json=heatingTargetTemperature,proto3" json:"heating_target_temperature,omitempty"`
	CoolingTargetTemperature         *Temperature           `protobuf:"bytes,10,opt,name=cooling_target_temperature,json=coolingTargetTemperature,proto3" json:"cooling_target_temperature,omitempty"`
	AntiCoolingTargetTemperature     *Temperature           `protobuf:"bytes,11,opt,name=anti_cooling_target_temperature,json=antiCoolingTargetTemperature,proto3" json:"anti_cooling_target_temperature,omitempty"`
	AutoModeHeatingTargetTemperature *Temperature           `protobuf:"bytes,12,opt,name=auto_mode_heating_target_temperature,json=autoModeHeatingTargetTemperature,proto3" json:"auto_mode_heating_target_temperature,omitempty"`
	AutoModeCoolingTargetTemperature *Temperature           `protobuf:"bytes,13,opt,name=auto_mode_cooling_target_temperature,json=autoModeCoolingTargetTemperature,proto3" json:"auto_mode_cooling_target_temperature,omitempty"`
	DisplayTemperatureUnits          TemperatureUnits       `protobuf:"varint,14,opt,name=display_temperature_units,json=displayTemperatureUnits,proto3,enum=fancoil.TemperatureUnits" json:"display_temperature_units,omitempty"`
	FloorHeatingMode                 FloorHeatingMode       `protobuf:"varint,15,opt,name=floor_heating_mode,json=floorHeatingMode,proto3,enum=fancoil.FloorHeatingMode" json:"floor_heating_mode,omitempty"`
	ModbusAddress                    *ModbusAddress         `protobuf:"bytes,16,opt,name=modbus_address,json=modbusAddress,proto3" json:"modbus_address,omitempty"`
	ValveState                       ValveState             `protobuf:"varint,17,opt,name=valve_state,json=valveState,proto3,enum=fancoil.ValveState" json:"valve_state,omitempty"`
	ValveSetting                     ValveSetting           `protobuf:"varint,18,opt,name=valve_setting,json=valveSetting,proto3,enum=fancoil.ValveSetting" json:"valve_setting,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{4}
}

func (x *State) GetSnapshotTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotTime
	}
	return nil
}

func (x *State) GetPowerStatus() PowerStatus {
	if x != nil {
		return x.PowerStatus
	}
	return PowerStatus_POWER_STATUS_UNSPECIFIED
}

func (x *State) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *State) GetRoomTemperature() *Temperature {
	if x != nil {
		return x.RoomTemperature
	}
	return nil
}

func (x *State) GetCoilTemperature() *Temperature {
	if x != nil {
		return x.CoilTemperature
	}
	return nil
}

func (x *State) GetPreferenceFanSetting() FanSetting {
	if x != nil {
		return x.PreferenceFanSetting
	}
	return FanSetting_FAN_SETTING_UNSPECIFIED
}

func (x *State) GetCurrentFanSetting() FanSetting {
	if x != nil {
		return x.CurrentFanSetting
	}
	return FanSetting_FAN_SETTING_UNSPECIFIED
}

func (x *State) GetFanSpeed() *FanSpeed {
	if x != nil {
		return x.FanSpeed
	}
	return nil
}

func (x *State) GetHeatingTargetTemperature() *Temperature {
	if x != nil {
		return x.HeatingTargetTemperature
	}
	return nil
}

func (x *State) GetCoolingTargetTemperature() *Temperature {
	if x != nil {
		return x.CoolingTargetTemperature
	}
	return nil
}

func (x *State) GetAntiCoolingTargetTemperature() *Temperature {
	if x != nil {
		return x.AntiCoolingTargetTemperature
	}
	return nil
}

func (x *State) GetAutoModeHeatingTargetTemperature() *Temperature {
	if x != nil {
		return x.AutoModeHeatingTargetTemperature
	}
	return nil
}

func (x *State) GetAutoModeCoolingTargetTemperature() *Temperature {
	if x != nil {
		return x.AutoModeCoolingTargetTemperature
	}
	return nil
}

func (x *State) GetDisplayTemperatureUnits() TemperatureUnits {
	if x != nil {
		return x.DisplayTemperatureUnits
	}
	return TemperatureUnits_TEMPERATURE_UNITS_UNSPECIFIED
}

func (x *State) GetFloorHeatingMode() FloorHeatingMode {
	if x != nil {
		return x.FloorHeatingMode
	}
	return FloorHeatingMode_FLOOR_HEATING_MODE_UNSPECIFIED
}

func (x *State) GetModbusAddress() *ModbusAddress {
	if x != nil {
		return x.ModbusAddress
	}
	return nil
}

func (x *State) GetValveState() ValveState {
	if x != nil {
		return x.ValveState
	}
	return ValveState_VALVE_STATE_UNSPECIFIED
}

func (x *State) GetValveSetting() ValveSetting {
	if x != nil {
		return x.ValveSetting
	}
	return ValveSetting_VALVE_SETTING_UNSPECIFIED
}

type SetStateRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	FancoilName              string                 `protobuf:"bytes,1,opt,name=fancoil_name,json=fancoilName,proto3" json:"fancoil_name,omitempty"`
	PowerStatus              PowerStatus            `protobuf:"varint,2,opt,name=power_status,json=powerStatus,proto3,enum=fancoil.PowerStatus" json:"power_status,omitempty"`
	PreferenceFanSetting     FanSetting             `protobuf:"varint,6,opt,name=preference_fan_setting,json=preferenceFanSetting,proto3,enum=fancoil.FanSetting" json:"preference_fan_setting,omitempty"`
	HeatingTargetTemperature *Temperature           `protobuf:"bytes,9,opt,name=heating_target_temperature,json=heatingTargetTemperature,proto3" json:"heating_target_temperature,omitempty"`
	CoolingTargetTemperature *Temperature           `protobuf:"bytes,10,opt,name=cooling_target_temperature,json=coolingTargetTemperature,proto3" json:"cooling_target_temperature,omitempty"`
	ValveSetting             ValveSetting           `protobuf:"varint,18,opt,name=valve_setting,json=valveSetting,proto3,enum=fancoil.ValveSetting" json:"valve_setting,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SetStateRequest) Reset() {
	*x = SetStateRequest{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateRequest) ProtoMessage() {}

func (x *SetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateRequest.ProtoReflect.Descriptor instead.
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{5}
}

func (x *SetStateRequest) GetFancoilName() string {
	if x != nil {
		return x.FancoilName
	}
	return ""
}

func (x *SetStateRequest) GetPowerStatus() PowerStatus {
	if x != nil {
		return x.PowerStatus
	}
	return PowerStatus_POWER_STATUS_UNSPECIFIED
}

func (x *SetStateRequest) GetPreferenceFanSetting() FanSetting {
	if x != nil {
		return x.PreferenceFanSetting
	}
	return FanSetting_FAN_SETTING_UNSPECIFIED
}

func (x *SetStateRequest) GetHeatingTargetTemperature() *Temperature {
	if x != nil {
		return x.HeatingTargetTemperature
	}
	return nil
}

func (x *SetStateRequest) GetCoolingTargetTemperature() *Temperature {
	if x != nil {
		return x.CoolingTargetTemperature
	}
	return nil
}

func (x *SetStateRequest) GetValveSetting() ValveSetting {
	if x != nil {
		return x.ValveSetting
	}
	return ValveSetting_VALVE_SETTING_UNSPECIFIED
}

type ModbusAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       uint32                 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModbusAddress) Reset() {
	*x = ModbusAddress{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModbusAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModbusAddress) ProtoMessage() {}

func (x *ModbusAddress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModbusAddress.ProtoReflect.Descriptor instead.
func (*ModbusAddress) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{6}
}

func (x *ModbusAddress) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

type SetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateResponse) Reset() {
	*x = SetStateResponse{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateResponse) ProtoMessage() {}

func (x *SetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateResponse.ProtoReflect.Descriptor instead.
func (*SetStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{7}
}

type Temperature struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DegreesCelcius float32                `protobuf:"fixed32,1,opt,name=degrees_celcius,json=degreesCelcius,proto3" json:"degrees_celcius,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Temperature) Reset() {
	*x = Temperature{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperature) ProtoMessage() {}

func (x *Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperature.ProtoReflect.Descriptor instead.
func (*Temperature) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{8}
}

func (x *Temperature) GetDegreesCelcius() float32 {
	if x != nil {
		return x.DegreesCelcius
	}
	return 0
}

type FanSpeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rpm           int64                  `protobuf:"varint,1,opt,name=rpm,proto3" json:"rpm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FanSpeed) Reset() {
	*x = FanSpeed{}
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FanSpeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FanSpeed) ProtoMessage() {}

func (x *FanSpeed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fancoil_fancoil_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FanSpeed.ProtoReflect.Descriptor instead.
func (*FanSpeed) Descriptor() ([]byte, []int) {
	return file_proto_fancoil_fancoil_proto_rawDescGZIP(), []int{9}
}

func (x *FanSpeed) GetRpm() int64 {
	if x != nil {
		return x.Rpm
	}
	return 0
}

var file_proto_fancoil_fancoil_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*ModbusEnumValueOptions)(nil),
		Field:         60000,
		Name:          "fancoil.modbus_options",
		Tag:           "bytes,60000,opt,name=modbus_options",
		Filename:      "proto/fancoil/fancoil.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional fancoil.ModbusEnumValueOptions modbus_options = 60000;
	E_ModbusOptions = &file_proto_fancoil_fancoil_proto_extTypes[0]
)

var File_proto_fancoil_fancoil_proto protoreflect.FileDescriptor

const file_proto_fancoil_fancoil_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/fancoil/fancoil.proto\x12\afancoil\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/descriptor.proto\"?\n" +
	"\x16ModbusEnumValueOptions\x12%\n" +
	"\x0eregister_value\x18\x01 \x01(\rR\rregisterValue\"4\n" +
	"\x0fGetStateRequest\x12!\n" +
	"\ffancoil_name\x18\x01 \x01(\tR\vfancoilName\"y\n" +
	"\x10GetStateResponse\x12$\n" +
	"\x05state\x18\x01 \x01(\v2\x0e.fancoil.StateR\x05state\x12?\n" +
	"\fraw_snapshot\x18\x02 \x01(\v2\x1c.fancoil.RawRegisterSnapshotR\vrawSnapshot\"\x9f\x01\n" +
	"\x13RawRegisterSnapshot\x12J\n" +
	"\n" +
	"raw_values\x18\x01 \x03(\v2+.fancoil.RawRegisterSnapshot.RawValuesEntryR\trawValues\x1a<\n" +
	"\x0eRawValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\x88\n" +
	"\n" +
	"\x05State\x12?\n" +
	"\rsnapshot_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fsnapshotTime\x127\n" +
	"\fpower_status\x18\x02 \x01(\x0e2\x14.fancoil.PowerStatusR\vpowerStatus\x12!\n" +
	"\x04mode\x18\x03 \x01(\x0e2\r.fancoil.ModeR\x04mode\x12?\n" +
	"\x10room_temperature\x18\x04 \x01(\v2\x14.fancoil.TemperatureR\x0froomTemperature\x12?\n" +
	"\x10coil_temperature\x18\x05 \x01(\v2\x14.fancoil.TemperatureR\x0fcoilTemperature\x12I\n" +
	"\x16preference_fan_setting\x18\x06 \x01(\x0e2\x13.fancoil.FanSettingR\x14preferenceFanSetting\x12C\n" +
	"\x13current_fan_setting\x18\a \x01(\x0e2\x13.fancoil.FanSettingR\x11currentFanSetting\x12.\n" +
	"\tfan_speed\x18\b \x01(\v2\x11.fancoil.FanSpeedR\bfanSpeed\x12R\n" +
	"\x1aheating_target_temperature\x18\t \x01(\v2\x14.fancoil.TemperatureR\x18heatingTargetTemperature\x12R\n" +
	"\x1acooling_target_temperature\x18\n" +
	" \x01(\v2\x14.fancoil.TemperatureR\x18coolingTargetTemperature\x12[\n" +
	"\x1fanti_cooling_target_temperature\x18\v \x01(\v2\x14.fancoil.TemperatureR\x1cantiCoolingTargetTemperature\x12d\n" +
	"$auto_mode_heating_target_temperature\x18\f \x01(\v2\x14.fancoil.TemperatureR autoModeHeatingTargetTemperature\x12d\n" +
	"$auto_mode_cooling_target_temperature\x18\r \x01(\v2\x14.fancoil.TemperatureR autoModeCoolingTargetTemperature\x12U\n" +
	"\x19display_temperature_units\x18\x0e \x01(\x0e2\x19.fancoil.TemperatureUnitsR\x17displayTemperatureUnits\x12G\n" +
	"\x12floor_heating_mode\x18\x0f \x01(\x0e2\x19.fancoil.FloorHeatingModeR\x10floorHeatingMode\x12=\n" +
	"\x0emodbus_address\x18\x10 \x01(\v2\x16.fancoil.ModbusAddressR\rmodbusAddress\x124\n" +
	"\vvalve_state\x18\x11 \x01(\x0e2\x13.fancoil.ValveStateR\n" +
	"valveState\x12:\n" +
	"\rvalve_setting\x18\x12 \x01(\x0e2\x15.fancoil.ValveSettingR\fvalveSetting\"\x9c\x03\n" +
	"\x0fSetStateRequest\x12!\n" +
	"\ffancoil_name\x18\x01 \x01(\tR\vfancoilName\x127\n" +
	"\fpower_status\x18\x02 \x01(\x0e2\x14.fancoil.PowerStatusR\vpowerStatus\x12I\n" +
	"\x16preference_fan_setting\x18\x06 \x01(\x0e2\x13.fancoil.FanSettingR\x14preferenceFanSetting\x12R\n" +
	"\x1aheating_target_temperature\x18\t \x01(\v2\x14.fancoil.TemperatureR\x18heatingTargetTemperature\x12R\n" +
	"\x1acooling_target_temperature\x18\n" +
	" \x01(\v2\x14.fancoil.TemperatureR\x18coolingTargetTemperature\x12:\n" +
	"\rvalve_setting\x18\x12 \x01(\x0e2\x15.fancoil.ValveSettingR\fvalveSetting\")\n" +
	"\rModbusAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\rR\aaddress\"\x12\n" +
	"\x10SetStateResponse\"6\n" +
	"\vTemperature\x12'\n" +
	"\x0fdegrees_celcius\x18\x01 \x01(\x02R\x0edegreesCelcius\"\x1c\n" +
	"\bFanSpeed\x12\x10\n" +
	"\x03rpm\x18\x01 \x01(\x03R\x03rpm*v\n" +
	"\x10TemperatureUnits\x12!\n" +
	"\x1dTEMPERATURE_UNITS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TEMPERATURE_UNITS_CELCIUS\x10\x01\x12 \n" +
	"\x1cTEMPERATURE_UNITS_FAHRENHEIT\x10\x02*m\n" +
	"\x10FloorHeatingMode\x12\"\n" +
	"\x1eFLOOR_HEATING_MODE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15FLOOR_HEATING_MODE_ON\x10\x01\x12\x1a\n" +
	"\x16FLOOR_HEATING_MODE_OFF\x10\x02*R\n" +
	"\n" +
	"ValveState\x12\x1b\n" +
	"\x17VALVE_STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eVALVE_STATE_ON\x10\x01\x12\x13\n" +
	"\x0fVALVE_STATE_OFF\x10\x02*r\n" +
	"\fValveSetting\x12\x1d\n" +
	"\x19VALVE_SETTING_UNSPECIFIED\x10\x00\x12!\n" +
	"\x15VALVE_SETTING_ENABLED\x10\x01\x1a\x06\x82\xa6\x1d\x02\b\x01\x12 \n" +
	"\x16VALVE_SETTING_DISABLED\x10\x02\x1a\x04\x82\xa6\x1d\x00*\xa4\t\n" +
	"\fRegisterName\x12\x1d\n" +
	"\x19REGISTER_NAME_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x14REGISTER_NAME_ON_OFF\x10\x8d\xdd\x01\x12\x18\n" +
	"\x12REGISTER_NAME_MODE\x10\x8e\xdd\x01\x12\x1c\n" +
	"\x16REGISTER_NAME_FANSPEED\x10\x8f\xdd\x01\x12\x1e\n" +
	"\x18REGISTER_NAME_TIMER_OFF1\x10\x92\xdd\x01\x12\x1e\n" +
	"\x18REGISTER_NAME_TIMER_OFF2\x10\x93\xdd\x01\x12'\n" +
	"!REGISTER_NAME_MAX_SET_TEMPERATURE\x10\x94\xdd\x01\x12'\n" +
	"!REGISTER_NAME_MIN_SET_TEMPERATURE\x10\x95\xdd\x01\x12+\n" +
	"%REGISTER_NAME_COOLING_SET_TEMPERATURE\x10\x96\xdd\x01\x12+\n" +
	"%REGISTER_NAME_HEATING_SET_TEMPERATURE\x10\x97\xdd\x01\x120\n" +
	"*REGISTER_NAME_COOLING_SET_TEMPERATURE_AUTO\x10\x98\xdd\x01\x120\n" +
	"*REGISTER_NAME_HEATING_SET_TEMPERATURE_AUTO\x10\x99\xdd\x01\x129\n" +
	"3REGISTER_NAME_ANTI_COOLING_WIND_SETTING_TEMPERATURE\x10\x9a\xdd\x01\x12'\n" +
	"!REGISTER_NAME_START_ANTI_HOT_WIND\x10\x9b\xdd\x01\x12(\n" +
	"\"REGISTER_NAME_START_ULTRA_LOW_WIND\x10\x9c\xdd\x01\x12\x1d\n" +
	"\x17REGISTER_NAME_USE_VALVE\x10\x9d\xdd\x01\x12%\n" +
	"\x1fREGISTER_NAME_USE_FLOOR_HEATING\x10\x9e\xdd\x01\x12\"\n" +
	"\x1cREGISTER_NAME_USE_FAHRENHEIT\x10\x9f\xdd\x01\x12 \n" +
	"\x1aREGISTER_NAME_MASTER_SLAVE\x10\xa0\xdd\x01\x12 \n" +
	"\x1aREGISTER_NAME_UNIT_ADDRESS\x10\xa1\xdd\x01\x12$\n" +
	"\x1eREGISTER_NAME_ROOM_TEMPERATURE\x10\xd1\xed\x02\x12$\n" +
	"\x1eREGISTER_NAME_COIL_TEMPERATURE\x10\xd2\xed\x02\x12%\n" +
	"\x1fREGISTER_NAME_CURRENT_FAN_SPEED\x10\xd3\xed\x02\x12\x1b\n" +
	"\x15REGISTER_NAME_FAN_RPM\x10\xd4\xed\x02\x12 \n" +
	"\x1aREGISTER_NAME_VALVE_ON_OFF\x10\xd5\xed\x02\x12!\n" +
	"\x1bREGISTER_NAME_REMOTE_ON_OFF\x10\xd6\xed\x02\x12%\n" +
	"\x1fREGISTER_NAME_SIMULATION_SIGNAL\x10\xd7\xed\x02\x123\n" +
	"-REGISTER_NAME_FAN_SPEED_SIGNAL_FEEDBACK_FAULT\x10\xd8\xed\x02\x121\n" +
	"+REGISTER_NAME_ROOM_TEMPERATURE_SENSOR_FAULT\x10\xd9\xed\x02\x121\n" +
	"+REGISTER_NAME_COIL_TEMPERATURE_SENSOR_FAULT\x10\xda\xed\x02*\xfd\x01\n" +
	"\n" +
	"FanSetting\x12\x1b\n" +
	"\x17FAN_SETTING_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x0fFAN_SETTING_OFF\x10\a\x1a\x04\x82\xa6\x1d\x00\x12!\n" +
	"\x15FAN_SETTING_ULTRA_LOW\x10\x01\x1a\x06\x82\xa6\x1d\x02\b\x01\x12\x1b\n" +
	"\x0fFAN_SETTING_LOW\x10\x02\x1a\x06\x82\xa6\x1d\x02\b\x02\x12\x1e\n" +
	"\x12FAN_SETTING_MEDIUM\x10\x03\x1a\x06\x82\xa6\x1d\x02\b\x03\x12\x1c\n" +
	"\x10FAN_SETTING_HIGH\x10\x04\x1a\x06\x82\xa6\x1d\x02\b\x04\x12\x1b\n" +
	"\x0fFAN_SETTING_MAX\x10\x05\x1a\x06\x82\xa6\x1d\x02\b\x05\x12\x1c\n" +
	"\x10FAN_SETTING_AUTO\x10\x06\x1a\x06\x82\xa6\x1d\x02\b\x06*V\n" +
	"\vPowerStatus\x12\x1c\n" +
	"\x18POWER_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPOWER_STATUS_ON\x10\x01\x12\x14\n" +
	"\x10POWER_STATUS_OFF\x10\x02*\x80\x01\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tMODE_AUTO\x10\x05\x12\x10\n" +
	"\fMODE_COOLING\x10\x01\x12\x19\n" +
	"\x15MODE_DEHUMIDIFICATION\x10\x02\x12\x14\n" +
	"\x10MODE_VENTILATION\x10\x03\x12\x10\n" +
	"\fMODE_HEATING\x10\x042\x96\x01\n" +
	"\x0eFanCoilService\x12A\n" +
	"\bGetState\x12\x18.fancoil.GetStateRequest\x1a\x19.fancoil.GetStateResponse\"\x00\x12A\n" +
	"\bSetState\x12\x18.fancoil.SetStateRequest\x1a\x19.fancoil.SetStateResponse\"\x00:k\n" +
	"\x0emodbus_options\x12!.google.protobuf.EnumValueOptions\x18\xe0\xd4\x03 \x01(\v2\x1f.fancoil.ModbusEnumValueOptionsR\rmodbusOptionsB-Z+github.com/gonzojive/heatpump/proto/fancoilb\x06proto3"

var (
	file_proto_fancoil_fancoil_proto_rawDescOnce sync.Once
	file_proto_fancoil_fancoil_proto_rawDescData []byte
)

func file_proto_fancoil_fancoil_proto_rawDescGZIP() []byte {
	file_proto_fancoil_fancoil_proto_rawDescOnce.Do(func() {
		file_proto_fancoil_fancoil_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fancoil_fancoil_proto_rawDesc), len(file_proto_fancoil_fancoil_proto_rawDesc)))
	})
	return file_proto_fancoil_fancoil_proto_rawDescData
}

var file_proto_fancoil_fancoil_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_proto_fancoil_fancoil_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_fancoil_fancoil_proto_goTypes = []any{
	(TemperatureUnits)(0),                 // 0: fancoil.TemperatureUnits
	(FloorHeatingMode)(0),                 // 1: fancoil.FloorHeatingMode
	(ValveState)(0),                       // 2: fancoil.ValveState
	(ValveSetting)(0),                     // 3: fancoil.ValveSetting
	(RegisterName)(0),                     // 4: fancoil.RegisterName
	(FanSetting)(0),                       // 5: fancoil.FanSetting
	(PowerStatus)(0),                      // 6: fancoil.PowerStatus
	(Mode)(0),                             // 7: fancoil.Mode
	(*ModbusEnumValueOptions)(nil),        // 8: fancoil.ModbusEnumValueOptions
	(*GetStateRequest)(nil),               // 9: fancoil.GetStateRequest
	(*GetStateResponse)(nil),              // 10: fancoil.GetStateResponse
	(*RawRegisterSnapshot)(nil),           // 11: fancoil.RawRegisterSnapshot
	(*State)(nil),                         // 12: fancoil.State
	(*SetStateRequest)(nil),               // 13: fancoil.SetStateRequest
	(*ModbusAddress)(nil),                 // 14: fancoil.ModbusAddress
	(*SetStateResponse)(nil),              // 15: fancoil.SetStateResponse
	(*Temperature)(nil),                   // 16: fancoil.Temperature
	(*FanSpeed)(nil),                      // 17: fancoil.FanSpeed
	nil,                                   // 18: fancoil.RawRegisterSnapshot.RawValuesEntry
	(*timestamppb.Timestamp)(nil),         // 19: google.protobuf.Timestamp
	(*descriptorpb.EnumValueOptions)(nil), // 20: google.protobuf.EnumValueOptions
}
var file_proto_fancoil_fancoil_proto_depIdxs = []int32{
	12, // 0: fancoil.GetStateResponse.state:type_name -> fancoil.State
	11, // 1: fancoil.GetStateResponse.raw_snapshot:type_name -> fancoil.RawRegisterSnapshot
	18, // 2: fancoil.RawRegisterSnapshot.raw_values:type_name -> fancoil.RawRegisterSnapshot.RawValuesEntry
	19, // 3: fancoil.State.snapshot_time:type_name -> google.protobuf.Timestamp
	6,  // 4: fancoil.State.power_status:type_name -> fancoil.PowerStatus
	7,  // 5: fancoil.State.mode:type_name -> fancoil.Mode
	16, // 6: fancoil.State.room_temperature:type_name -> fancoil.Temperature
	16, // 7: fancoil.State.coil_temperature:type_name -> fancoil.Temperature
	5,  // 8: fancoil.State.preference_fan_setting:type_name -> fancoil.FanSetting
	5,  // 9: fancoil.State.current_fan_setting:type_name -> fancoil.FanSetting
	17, // 10: fancoil.State.fan_speed:type_name -> fancoil.FanSpeed
	16, // 11: fancoil.State.heating_target_temperature:type_name -> fancoil.Temperature
	16, // 12: fancoil.State.cooling_target_temperature:type_name -> fancoil.Temperature
	16, // 13: fancoil.State.anti_cooling_target_temperature:type_name -> fancoil.Temperature
	16, // 14: fancoil.State.auto_mode_heating_target_temperature:type_name -> fancoil.Temperature
	16, // 15: fancoil.State.auto_mode_cooling_target_temperature:type_name -> fancoil.Temperature
	0,  // 16: fancoil.State.display_temperature_units:type_name -> fancoil.TemperatureUnits
	1,  // 17: fancoil.State.floor_heating_mode:type_name -> fancoil.FloorHeatingMode
	14, // 18: fancoil.State.modbus_address:type_name -> fancoil.ModbusAddress
	2,  // 19: fancoil.State.valve_state:type_name -> fancoil.ValveState
	3,  // 20: fancoil.State.valve_setting:type_name -> fancoil.ValveSetting
	6,  // 21: fancoil.SetStateRequest.power_status:type_name -> fancoil.PowerStatus
	5,  // 22: fancoil.SetStateRequest.preference_fan_setting:type_name -> fancoil.FanSetting
	16, // 23: fancoil.SetStateRequest.heating_target_temperature:type_name -> fancoil.Temperature
	16, // 24: fancoil.SetStateRequest.cooling_target_temperature:type_name -> fancoil.Temperature
	3,  // 25: fancoil.SetStateRequest.valve_setting:type_name -> fancoil.ValveSetting
	20, // 26: fancoil.modbus_options:extendee -> google.protobuf.EnumValueOptions
	8,  // 27: fancoil.modbus_options:type_name -> fancoil.ModbusEnumValueOptions
	9,  // 28: fancoil.FanCoilService.GetState:input_type -> fancoil.GetStateRequest
	13, // 29: fancoil.FanCoilService.SetState:input_type -> fancoil.SetStateRequest
	10, // 30: fancoil.FanCoilService.GetState:output_type -> fancoil.GetStateResponse
	15, // 31: fancoil.FanCoilService.SetState:output_type -> fancoil.SetStateResponse
	30, // [30:32] is the sub-list for method output_type
	28, // [28:30] is the sub-list for method input_type
	27, // [27:28] is the sub-list for extension type_name
	26, // [26:27] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_fancoil_fancoil_proto_init() }
func file_proto_fancoil_fancoil_proto_init() {
	if File_proto_fancoil_fancoil_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fancoil_fancoil_proto_rawDesc), len(file_proto_fancoil_fancoil_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   11,
			NumExtensions: 1,
			NumServices:   1,
		},
		GoTypes:           file_proto_fancoil_fancoil_proto_goTypes,
		DependencyIndexes: file_proto_fancoil_fancoil_proto_depIdxs,
		EnumInfos:         file_proto_fancoil_fancoil_proto_enumTypes,
		MessageInfos:      file_proto_fancoil_fancoil_proto_msgTypes,
		ExtensionInfos:    file_proto_fancoil_fancoil_proto_extTypes,
	}.Build()
	File_proto_fancoil_fancoil_proto = out.File
	file_proto_fancoil_fancoil_proto_goTypes = nil
	file_proto_fancoil_fancoil_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FanCoilServiceClient is the client API for FanCoilService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FanCoilServiceClient interface {
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error)
}

type fanCoilServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFanCoilServiceClient(cc grpc.ClientConnInterface) FanCoilServiceClient {
	return &fanCoilServiceClient{cc}
}

func (c *fanCoilServiceClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, "/fancoil.FanCoilService/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fanCoilServiceClient) SetState(ctx context.Context, in *SetStateRequest, opts ...grpc.CallOption) (*SetStateResponse, error) {
	out := new(SetStateResponse)
	err := c.cc.Invoke(ctx, "/fancoil.FanCoilService/SetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FanCoilServiceServer is the server API for FanCoilService service.
type FanCoilServiceServer interface {
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	SetState(context.Context, *SetStateRequest) (*SetStateResponse, error)
}

// UnimplementedFanCoilServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFanCoilServiceServer struct {
}

func (*UnimplementedFanCoilServiceServer) GetState(context.Context, *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (*UnimplementedFanCoilServiceServer) SetState(context.Context, *SetStateRequest) (*SetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetState not implemented")
}

func RegisterFanCoilServiceServer(s *grpc.Server, srv FanCoilServiceServer) {
	s.RegisterService(&_FanCoilService_serviceDesc, srv)
}

func _FanCoilService_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanCoilServiceServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fancoil.FanCoilService/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanCoilServiceServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FanCoilService_SetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FanCoilServiceServer).SetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fancoil.FanCoilService/SetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FanCoilServiceServer).SetState(ctx, req.(*SetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FanCoilService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fancoil.FanCoilService",
	HandlerType: (*FanCoilServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _FanCoilService_GetState_Handler,
		},
		{
			MethodName: "SetState",
			Handler:    _FanCoilService_SetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fancoil/fancoil.proto",
}
