// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: proto/controller/controller.proto

package controller

import (
	context "context"
	fancoil "github.com/gonzojive/heatpump/proto/fancoil"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDeviceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStateRequest) Reset() {
	*x = GetDeviceStateRequest{}
	mi := &file_proto_controller_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStateRequest) ProtoMessage() {}

func (x *GetDeviceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStateRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{0}
}

func (x *GetDeviceStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeviceState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FancoilState  *fancoil.State         `protobuf:"bytes,2,opt,name=fancoil_state,json=fancoilState,proto3" json:"fancoil_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceState) Reset() {
	*x = DeviceState{}
	mi := &file_proto_controller_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceState) ProtoMessage() {}

func (x *DeviceState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceState.ProtoReflect.Descriptor instead.
func (*DeviceState) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceState) GetFancoilState() *fancoil.State {
	if x != nil {
		return x.FancoilState
	}
	return nil
}

type SetDeviceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *DeviceState           `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceStateRequest) Reset() {
	*x = SetDeviceStateRequest{}
	mi := &file_proto_controller_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceStateRequest) ProtoMessage() {}

func (x *SetDeviceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceStateRequest.ProtoReflect.Descriptor instead.
func (*SetDeviceStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{2}
}

func (x *SetDeviceStateRequest) GetState() *DeviceState {
	if x != nil {
		return x.State
	}
	return nil
}

type SetDeviceStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeviceStateResponse) Reset() {
	*x = SetDeviceStateResponse{}
	mi := &file_proto_controller_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeviceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeviceStateResponse) ProtoMessage() {}

func (x *SetDeviceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeviceStateResponse.ProtoReflect.Descriptor instead.
func (*SetDeviceStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{3}
}

type Configuration struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	CloudIotDeviceName       string                 `protobuf:"bytes,1,opt,name=cloud_iot_device_name,json=cloudIotDeviceName,proto3" json:"cloud_iot_device_name,omitempty"`
	HeatpumpModbusDevicePath string                 `protobuf:"bytes,2,opt,name=heatpump_modbus_device_path,json=heatpumpModbusDevicePath,proto3" json:"heatpump_modbus_device_path,omitempty"`
	FanCoilsModbusDevicePath string                 `protobuf:"bytes,3,opt,name=fan_coils_modbus_device_path,json=fanCoilsModbusDevicePath,proto3" json:"fan_coils_modbus_device_path,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_proto_controller_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{4}
}

func (x *Configuration) GetCloudIotDeviceName() string {
	if x != nil {
		return x.CloudIotDeviceName
	}
	return ""
}

func (x *Configuration) GetHeatpumpModbusDevicePath() string {
	if x != nil {
		return x.HeatpumpModbusDevicePath
	}
	return ""
}

func (x *Configuration) GetFanCoilsModbusDevicePath() string {
	if x != nil {
		return x.FanCoilsModbusDevicePath
	}
	return ""
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*Command_SetStateRequest
	Command       isCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_controller_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetCommand() isCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *Command) GetSetStateRequest() *fancoil.SetStateRequest {
	if x != nil {
		if x, ok := x.Command.(*Command_SetStateRequest); ok {
			return x.SetStateRequest
		}
	}
	return nil
}

type isCommand_Command interface {
	isCommand_Command()
}

type Command_SetStateRequest struct {
	SetStateRequest *fancoil.SetStateRequest `protobuf:"bytes,1,opt,name=set_state_request,json=setStateRequest,proto3,oneof"`
}

func (*Command_SetStateRequest) isCommand_Command() {}

type DeviceAccessToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Expiration    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceAccessToken) Reset() {
	*x = DeviceAccessToken{}
	mi := &file_proto_controller_controller_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceAccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAccessToken) ProtoMessage() {}

func (x *DeviceAccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAccessToken.ProtoReflect.Descriptor instead.
func (*DeviceAccessToken) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceAccessToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeviceAccessToken) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

func (x *DeviceAccessToken) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type ExtendTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendTokenRequest) Reset() {
	*x = ExtendTokenRequest{}
	mi := &file_proto_controller_controller_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendTokenRequest) ProtoMessage() {}

func (x *ExtendTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendTokenRequest.ProtoReflect.Descriptor instead.
func (*ExtendTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{7}
}

func (x *ExtendTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ExtendTokenResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RefreshedToken string                 `protobuf:"bytes,1,opt,name=refreshed_token,json=refreshedToken,proto3" json:"refreshed_token,omitempty"`
	Expiration     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiration,proto3" json:"expiration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExtendTokenResponse) Reset() {
	*x = ExtendTokenResponse{}
	mi := &file_proto_controller_controller_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendTokenResponse) ProtoMessage() {}

func (x *ExtendTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_controller_controller_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendTokenResponse.ProtoReflect.Descriptor instead.
func (*ExtendTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_controller_controller_proto_rawDescGZIP(), []int{8}
}

func (x *ExtendTokenResponse) GetRefreshedToken() string {
	if x != nil {
		return x.RefreshedToken
	}
	return ""
}

func (x *ExtendTokenResponse) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

var File_proto_controller_controller_proto protoreflect.FileDescriptor

const file_proto_controller_controller_proto_rawDesc = "" +
	"\n" +
	"!proto/controller/controller.proto\x12\n" +
	"controller\x1a\x1bproto/fancoil/fancoil.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"+\n" +
	"\x15GetDeviceStateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"V\n" +
	"\vDeviceState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x123\n" +
	"\rfancoil_state\x18\x02 \x01(\v2\x0e.fancoil.StateR\ffancoilState\"F\n" +
	"\x15SetDeviceStateRequest\x12-\n" +
	"\x05state\x18\x01 \x01(\v2\x17.controller.DeviceStateR\x05state\"\x18\n" +
	"\x16SetDeviceStateResponse\"\xc1\x01\n" +
	"\rConfiguration\x121\n" +
	"\x15cloud_iot_device_name\x18\x01 \x01(\tR\x12cloudIotDeviceName\x12=\n" +
	"\x1bheatpump_modbus_device_path\x18\x02 \x01(\tR\x18heatpumpModbusDevicePath\x12>\n" +
	"\x1cfan_coils_modbus_device_path\x18\x03 \x01(\tR\x18fanCoilsModbusDevicePath\"\\\n" +
	"\aCommand\x12F\n" +
	"\x11set_state_request\x18\x01 \x01(\v2\x18.fancoil.SetStateRequestH\x00R\x0fsetStateRequestB\t\n" +
	"\acommand\"\x86\x01\n" +
	"\x11DeviceAccessToken\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12:\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\"*\n" +
	"\x12ExtendTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"z\n" +
	"\x13ExtendTokenResponse\x12'\n" +
	"\x0frefreshed_token\x18\x01 \x01(\tR\x0erefreshedToken\x12:\n" +
	"\n" +
	"expiration\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiration2\xb9\x01\n" +
	"\fStateService\x12N\n" +
	"\x0eGetDeviceState\x12!.controller.GetDeviceStateRequest\x1a\x17.controller.DeviceState\"\x00\x12Y\n" +
	"\x0eSetDeviceState\x12!.controller.SetDeviceStateRequest\x1a\".controller.SetDeviceStateResponse\"\x002_\n" +
	"\vAuthService\x12P\n" +
	"\vExtendToken\x12\x1e.controller.ExtendTokenRequest\x1a\x1f.controller.ExtendTokenResponse\"\x00B0Z.github.com/gonzojive/heatpump/proto/controllerb\x06proto3"

var (
	file_proto_controller_controller_proto_rawDescOnce sync.Once
	file_proto_controller_controller_proto_rawDescData []byte
)

func file_proto_controller_controller_proto_rawDescGZIP() []byte {
	file_proto_controller_controller_proto_rawDescOnce.Do(func() {
		file_proto_controller_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_controller_controller_proto_rawDesc), len(file_proto_controller_controller_proto_rawDesc)))
	})
	return file_proto_controller_controller_proto_rawDescData
}

var file_proto_controller_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_controller_controller_proto_goTypes = []any{
	(*GetDeviceStateRequest)(nil),   // 0: controller.GetDeviceStateRequest
	(*DeviceState)(nil),             // 1: controller.DeviceState
	(*SetDeviceStateRequest)(nil),   // 2: controller.SetDeviceStateRequest
	(*SetDeviceStateResponse)(nil),  // 3: controller.SetDeviceStateResponse
	(*Configuration)(nil),           // 4: controller.Configuration
	(*Command)(nil),                 // 5: controller.Command
	(*DeviceAccessToken)(nil),       // 6: controller.DeviceAccessToken
	(*ExtendTokenRequest)(nil),      // 7: controller.ExtendTokenRequest
	(*ExtendTokenResponse)(nil),     // 8: controller.ExtendTokenResponse
	(*fancoil.State)(nil),           // 9: fancoil.State
	(*fancoil.SetStateRequest)(nil), // 10: fancoil.SetStateRequest
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_proto_controller_controller_proto_depIdxs = []int32{
	9,  // 0: controller.DeviceState.fancoil_state:type_name -> fancoil.State
	1,  // 1: controller.SetDeviceStateRequest.state:type_name -> controller.DeviceState
	10, // 2: controller.Command.set_state_request:type_name -> fancoil.SetStateRequest
	11, // 3: controller.DeviceAccessToken.expiration:type_name -> google.protobuf.Timestamp
	11, // 4: controller.ExtendTokenResponse.expiration:type_name -> google.protobuf.Timestamp
	0,  // 5: controller.StateService.GetDeviceState:input_type -> controller.GetDeviceStateRequest
	2,  // 6: controller.StateService.SetDeviceState:input_type -> controller.SetDeviceStateRequest
	7,  // 7: controller.AuthService.ExtendToken:input_type -> controller.ExtendTokenRequest
	1,  // 8: controller.StateService.GetDeviceState:output_type -> controller.DeviceState
	3,  // 9: controller.StateService.SetDeviceState:output_type -> controller.SetDeviceStateResponse
	8,  // 10: controller.AuthService.ExtendToken:output_type -> controller.ExtendTokenResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_controller_controller_proto_init() }
func file_proto_controller_controller_proto_init() {
	if File_proto_controller_controller_proto != nil {
		return
	}
	file_proto_controller_controller_proto_msgTypes[5].OneofWrappers = []any{
		(*Command_SetStateRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_controller_controller_proto_rawDesc), len(file_proto_controller_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_controller_controller_proto_goTypes,
		DependencyIndexes: file_proto_controller_controller_proto_depIdxs,
		MessageInfos:      file_proto_controller_controller_proto_msgTypes,
	}.Build()
	File_proto_controller_controller_proto = out.File
	file_proto_controller_controller_proto_goTypes = nil
	file_proto_controller_controller_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StateServiceClient is the client API for StateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StateServiceClient interface {
	GetDeviceState(ctx context.Context, in *GetDeviceStateRequest, opts ...grpc.CallOption) (*DeviceState, error)
	SetDeviceState(ctx context.Context, in *SetDeviceStateRequest, opts ...grpc.CallOption) (*SetDeviceStateResponse, error)
}

type stateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStateServiceClient(cc grpc.ClientConnInterface) StateServiceClient {
	return &stateServiceClient{cc}
}

func (c *stateServiceClient) GetDeviceState(ctx context.Context, in *GetDeviceStateRequest, opts ...grpc.CallOption) (*DeviceState, error) {
	out := new(DeviceState)
	err := c.cc.Invoke(ctx, "/controller.StateService/GetDeviceState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stateServiceClient) SetDeviceState(ctx context.Context, in *SetDeviceStateRequest, opts ...grpc.CallOption) (*SetDeviceStateResponse, error) {
	out := new(SetDeviceStateResponse)
	err := c.cc.Invoke(ctx, "/controller.StateService/SetDeviceState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StateServiceServer is the server API for StateService service.
type StateServiceServer interface {
	GetDeviceState(context.Context, *GetDeviceStateRequest) (*DeviceState, error)
	SetDeviceState(context.Context, *SetDeviceStateRequest) (*SetDeviceStateResponse, error)
}

// UnimplementedStateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStateServiceServer struct {
}

func (*UnimplementedStateServiceServer) GetDeviceState(context.Context, *GetDeviceStateRequest) (*DeviceState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceState not implemented")
}
func (*UnimplementedStateServiceServer) SetDeviceState(context.Context, *SetDeviceStateRequest) (*SetDeviceStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDeviceState not implemented")
}

func RegisterStateServiceServer(s *grpc.Server, srv StateServiceServer) {
	s.RegisterService(&_StateService_serviceDesc, srv)
}

func _StateService_GetDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).GetDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.StateService/GetDeviceState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).GetDeviceState(ctx, req.(*GetDeviceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StateService_SetDeviceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeviceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StateServiceServer).SetDeviceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.StateService/SetDeviceState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StateServiceServer).SetDeviceState(ctx, req.(*SetDeviceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.StateService",
	HandlerType: (*StateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceState",
			Handler:    _StateService_GetDeviceState_Handler,
		},
		{
			MethodName: "SetDeviceState",
			Handler:    _StateService_SetDeviceState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/controller/controller.proto",
}

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	ExtendToken(ctx context.Context, in *ExtendTokenRequest, opts ...grpc.CallOption) (*ExtendTokenResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) ExtendToken(ctx context.Context, in *ExtendTokenRequest, opts ...grpc.CallOption) (*ExtendTokenResponse, error) {
	out := new(ExtendTokenResponse)
	err := c.cc.Invoke(ctx, "/controller.AuthService/ExtendToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	ExtendToken(context.Context, *ExtendTokenRequest) (*ExtendTokenResponse, error)
}

// UnimplementedAuthServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (*UnimplementedAuthServiceServer) ExtendToken(context.Context, *ExtendTokenRequest) (*ExtendTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendToken not implemented")
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_ExtendToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ExtendToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controller.AuthService/ExtendToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ExtendToken(ctx, req.(*ExtendTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controller.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtendToken",
			Handler:    _AuthService_ExtendToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/controller/controller.proto",
}
